
- name: Copy Redis Yum Repo file
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install Redis
  ansible.builtin.yum:
    name: redis-6.2.7
    state: installed

- name: Update the Listen Address in Redis Config
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.conf

- name: Start Redis Service
  ansible.builtin.systemd:
    state: restarted
    name: redis
    enabled: yes