
- name: Setup Yum Repo
  ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name:
        - nodejs
        - gcc-c++
    state: installed

- name: Add a Application User
  ansible.builtin.user:
    name: roboshop

- name: Download and Extract catalogue content
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/catalogue/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Clean old Catalogue content
  ansible.builtin.file:
    path: /home/roboshop/catalogue
    state: absent

- name: Copy Catalogue Code
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue
    remote_src: yes
  become_user: roboshop

- name: Install NodeJS Dependencies
  community.general.npm:
      path: /home/roboshop/catalogue

#- name: Start MongoDB Service
#  ansible.builtin.systemd:
#    state: restarted
#    name: mongod
#    enabled: yes

