
- name: Setup Yum Repo
  ansible.builtin.shell: https://rpm.nodesource.com/setup_lts.x | bash

- name: Install NodeJS
  ansible.builtin.yum:
    name:
      - nodejs
      - gcc-c++
    state: installed

- name: Download from Github
  import_role:
    name: common
    tasks_from: download-from-github

- name: Install NodeJS Dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}

- name: Systemd Setup
  import_role:
    name: common
    tasks_from: systemd

