- name: Install Python
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python3-devel
    state: installed

- name: Download from Github
  import_role:
    name: common
    tasks_from: download-from-github

- name: Python Dependencies
    pip:
      requirements: /home/roboshop/{{COMPONENT}}/requirements.txt
      executable: pip3

- name: Print
  debug:
    msg: {{APPUSER}}

- name: Systemd Setup
  import_role:
    name: common
    tasks_from: systemd
